version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: tokimikichika-find-backend
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - backend_vendor:/var/www/html/vendor
    expose:
      - "9000"
    networks:
      - appnet

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: tokimikichika-find-nginx
    depends_on:
      - backend
    ports:
      - "6123:80"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
  
volumes:
  backend_vendor:
    driver: local



