version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: tokimikichika-find-backend
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - backend_vendor:/var/www/html/vendor
    expose:
      - "9000"
    networks:
      - appnet

  node:
    image: node:20-alpine
    container_name: tokimikichika-find-node
    working_dir: /app
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0"
    expose:
      - "5173"
    networks:
      - appnet

  nginx:
    image: nginx:1.27-alpine
    container_name: tokimikichika-find-nginx
    depends_on:
      - backend
      - node
    ports:
      - "6123:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
  
volumes:
  backend_vendor:
    driver: local
  node_modules:
    driver: local



